# Generated by Django 4.0.5 on 2022-06-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_product_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
