# Generated by Django 4.0.5 on 2022-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publishDate',
            field=models.DateField(null=True),
        ),
    ]
