# Generated by Django 4.0.5 on 2022-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_address_user_email_user_number_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
