# Generated by Django 4.0.5 on 2022-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_desc_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
