# Generated by Django 4.0.5 on 2022-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
