# Generated by Django 4.0.5 on 2022-06-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_name_order_order_name_alter_order_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateOrder',
            fields=[
                ('update_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(max_length=122, null=True)),
                ('update_desc', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
