# Generated by Django 4.0.5 on 2022-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_updateorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='updateorder',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
