# Generated by Django 4.0.5 on 2022-06-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(max_length=122, primary_key=True, serialize=False),
        ),
    ]
