# Generated by Django 4.0.5 on 2022-06-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
