# Generated by Django 4.0.5 on 2022-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
