# Generated by Django 4.0.5 on 2022-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_orders_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('address1', models.CharField(max_length=122, null=True)),
                ('address2', models.CharField(max_length=122, null=True)),
                ('city', models.CharField(max_length=122, null=True)),
                ('state', models.CharField(max_length=122, null=True)),
                ('zip', models.CharField(max_length=133, null=True)),
                ('number', models.CharField(max_length=133, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AlterField(
            model_name='updateorder',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
