# Generated by Django 4.0.5 on 2022-06-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_delete_orders_alter_updateorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateorder',
            name='order_id',
        ),
    ]
