# Generated by Django 4.0.5 on 2022-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_updateorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateorder',
            name='order_id',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
