# Generated by Django 4.0.5 on 2022-06-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updateOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
